name: fundamental_submission1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  logger: ^2.6.1
  provider: ^6.1.5+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: font/Poppins-Bold.ttf
          weight: 700
        - asset: font/Poppins-SemiBold.ttf
          weight: 600
        - asset: font/Poppins-Medium.ttf
          weight: 500
        - asset: font/Poppins-Regular.ttf
          weight: 400
        - asset: font/Poppins-Light.ttf
          weight: 300
        - asset: font/Poppins-ExtraLight.ttf
          weight: 200
        - asset: font/Poppins-Thin.ttf
          weight: 100
